replicaCount: 1

webapp:
  name: ncote-app
  group: ncote-app
  path: /
  tls:
    fqdn: ncote.k8s.ucar.edu
    secretName: incommon-key-ncote
  volume1:
    name: campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    readOnly: true
  container: 
    image: hub.k8s.ucar.edu/ncote/data-flask:2024-10-04.22.03
    port: 5000
    memory: 1G
    cpu: 2