replicaCount: 1

webapp:
  name: ncote
  group: ncote
  path: /
  tls:
    fqdn: ncote.k8s.ucar.edu
    secretName: incommon-key-ncote
  volume1:
    name: collections
    server: gladedm1.ucar.edu
    path: /gpfs/fs1/collections
    readOnly: true
  volume2:
    name: campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    readOnly: true
  container: 
    image: ncote/data-flask:2024-01-26.20.38
    port: 5000
    memory: 1G
    cpu: 2