apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: test-email-routing
  namespace: ncote
  labels:
    alertmanagerConfig: test
spec:
  route:
    receiver: ncote-test
    groupBy:
      - namespace
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 5m 
    matchers:
      - name: namespace
        value: ncote
        matchType: "="

  receivers:
    - name: ncote-test
      email_configs:
        - to: ncote@ucar.edu 
          from: alertmanager@k8s.ucar.edu
          smarthost: vdir.ucar.edu:25  