apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      volumes:
      - name: tomcat-config
        configMap:
          name: {{ .Values.webapp.name }}-tomcat-config
      - name: shared-tmp
        emptyDir: {}
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        resources:
          limits:
            memory: {{ .Values.webapp.container.memory }}
            cpu: {{ .Values.webapp.container.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        volumeMounts:
        - name: tomcat-config
          mountPath: /usr/local/tomcat/conf/server.xml
          subPath: server.xml
        - name: shared-tmp
          mountPath: /tmp
      - name: log-tailer
        image: busybox
        command: ["/bin/sh"]
        args:
        - -c
        - |
            while true; do
            if [ -f /tmp/stdout.log ]; then
                tail -F /tmp/stdout.log
            else
                sleep 1
            fi
            done
        volumeMounts:
        - name: shared-tmp
            mountPath: /tmp