replicaCount: 1

webapp:
  name: ncote-test-app
  group: ncote-test-app
  path: /
  tls:
    fqdn: ncote-test.ncote.k8s.ucar.edu
    secretName: incommon-account-key
  volume1:
    name: campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    readOnly: true
  container: 
    image: docker.io/ncote/data-flask:2025-06-09
    port: 5000
    memory: 4G
    cpu: 2
db:
  superuser: 
    usernameKey: suname
    passwordKey: supass
    secretPath: flask-db-demo
  owner:
    name: app 
    passwordKey: password
    secretPath: flask-db-demo
