replicaCount: 1

webapp:
  name: ncar-viz-test
  group: ncar-viz-test
  path: /
  tls:
    fqdn: ncote-test.k8s.ucar.edu
    secretName: incommon-account-key
  volume1:
    name: collections
    server: gladedm1.ucar.edu
    path: /gpfs/fs1/collections
    readOnly: true
  volume2:
    name: campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    readOnly: true
  container: 
    image: hub.k8s.ucar.edu/docker/ncote/data-flask-dev:2024-01-26.20.51
    port: 5000
    memory: 1G
    cpu: 2