replicaCount: 1

webapp:
  name: ncote-test-app
  group: ncote-test-app
  path: /
  tls:
    fqdn: ncote-test.k8s.ucar.edu
    secretName: incommon-account-key
  volume1:
    name: campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    readOnly: true
  container: 
    image: hub.k8s.ucar.edu/ncote/data-flask-dev:2025-08-08.21.03
    port: 5000
    memory: 4G
    cpu: 2
db:
  superuser: 
    usernameKey: suname
    passwordKey: supass
    secretPath: ncote@ucar.edu/flask-db-demo
  owner:
    name: ncote 
    usernameKey: username
    passwordKey: password
    secretPath: ncote@ucar.edu/flask-db-demo
