replicaCount: 1

webapp:
  name: ncote-test-app
  group: ncote-test-app
  path: /
  tls:
    fqdn: ncote-test.k8s.ucar.edu
    secretName: incommon-account-key
  volume1:
    name: collections
    server: gladedm1.ucar.edu
    path: /gpfs/fs1/collections
    readOnly: true
  volume2:
    name: campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    readOnly: true
  container: 
    image: hub.k8s.ucar.edu/docker/ncote/data-flask-dev:2024-02-09.17.43
    port: 5000
    memory: 4G
    cpu: 2