apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
      - {{ .Values.webapp.tls.fqdn }} 
      - ncote-test.ucar.edu
      secretName: {{ .Values.webapp.name }}-tls
  rules:
  - host: {{ .Values.webapp.tls.fqdn }}
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-active
            port:
              number: {{ .Values.webapp.container.port }}
  - host: ncote-test.ucar.edu  # Add this rule
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-active
            port:
              number: {{ .Values.webapp.container.port }}