apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.webapp.name }}-pgdb
  namespace: {{ .Release.Namespace }}
spec:
  enableSuperuserAccess: true
  instances: 2
  storage:
    size: 1Gi
    storageClass: ceph-kubepv

  postgresql:
    parameters:
      max_connections: "200"
    pg_hba:
      - "host all all 0.0.0.0/0 md5"
        
  superuserSecret:
    name: {{ .Values.webapp.name }}-superuser