apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ncote-test-app-pv
    namespace: {{ .Release.Namespace}}
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: mlceph-kubepv
    resources:
        requests:
            storage: 2Gi