apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webapp.name }}-superuser
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: |
    {{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-superuser-source" .Values.webapp.name)) -}}
    {{- if $secret -}}
    {{- $secret.data.username | b64dec -}}
    {{- else -}}
    postgres
    {{- end }}
  password: |
    {{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-superuser-source" .Values.webapp.name)) -}}
    {{- if $secret -}}
    {{- $secret.data.password | b64dec -}}
    {{- else -}}
    fallback-password
    {{- end }}