apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}-preview
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.webapp.container.port }}