apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    blueGreen:
      activeService: {{ .Values.webapp.name }}-active
      previewService: {{ .Values.webapp.name }}-preview
      autoPromotionEnabled: false  # Manual promotion for testing
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates: []
        args: []
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      volumes:
        - name: {{ .Values.webapp.name }}-pvctest
          persistentVolumeClaim:
            claimName: {{ .Values.webapp.name }}-pvctest
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        resources:
          limits:
            memory: {{ .Values.webapp.container.memory }}
            cpu: {{ .Values.webapp.container.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        volumeMounts:
        - mountPath: /pvc
          name: {{ .Values.webapp.name }}-pvctest
        env:
        - name: DB_HOST
          value: {{ .Values.db.name }}.k8s.ucar.edu
        - name: DB_NAME
          value: {{ .Values.db.database }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.name }}-app-user
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.name }}-app-user
              key: password