apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.webapp.name }}-pgdb
  namespace: {{ .Release.Namespace }}
spec:
  instances: 2
  storage:
    size: 1Gi
    
  bootstrap:
    initdb:
      database: {{ .Values.db.database }}
      owner: {{ .Values.db.owner }}
      secret:
        name: {{ .Values.webapp.name }}-app-user
        
  superuserSecret:
    name: {{ .Values.webapp.name }}-superuser