apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-external
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.db.name }}.k8s.ucar.edu"
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: {{ .Values.db.name }}
    cnpg.io/instanceRole: primary
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: {{ .Values.db.nodePort | default 31432 }}