apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.host }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.host }}
    group: {{ .Values.webapp.group }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.host }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.host }}
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres/postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.webapp.name }}-esos
              key: {{ .Values.db.passwordKey }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.db.volume.name }}
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
