apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
spec:
  type: CLusterIP
  ports:
  - port: 5432
  selector:
    app: {{ .Values.db.name }}