apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.webapp.name }}-pvctest
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-kubepv
  resources:
    requests:
      storage: 1Gi