replicaCount: 1

webapp:
  name: ncote-db-test
  group: ncote-db-test
  path: /
  tls:
    fqdn: ncote-db-test.k8s.ucar.edu
    secretName: incommon-cert-ncote-db-test
  preview:
    tls:
      fqdn: ncote-db-test-preview.k8s.ucar.edu
      secretName: ncote-db-test-preview-tls
  container: 
    image: docker.io/ncote/flask-db-demo:2026-05-26.21.18
    port: 5000
    memory: 1G
    cpu: 2
db:
  host: flask-db-demo
  owner: ncote
  database: test-db
  name: ncotesdb
  usernameKey: username
  passwordKey: password
  secretPath: ncote@ucar.edu/flask-db-demo
  superuser: 
    usernameKey: suname
    passwordKey: supass
    secretPath: ncote@ucar.edu/flask-db-demo
  volume:
    name: flask-db-demo-pv
    size: 1Gi