apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Values.webapp.name }}-alerting
  namespace: {{ .Release.Namespace }}
  labels:
    alertmanagerConfig: {{ .Values.webapp.name }}
    namespace: {{ .Release.Namespace }}
spec:
  route:
    receiver: {{ .Values.webapp.name }}-notifications
    groupBy:
      - alertname
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 60m 
    matchers:
      - name: namespace
        value: {{ .Release.Namespace }}
        matchType: "="

  receivers:
    - name: {{ .Values.webapp.name }}-notifications
      emailConfigs:
        - to: {{ .Values.alerting.email }}
          from: alertmanager@k8s.ucar.edu
          smarthost: vdir.ucar.edu:25