apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}-flower
spec:
  selector:
    app: {{ .Values.webapp.name }}-flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555