apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    group: {{ .Values.webapp.group }}
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  selector:
    app: redis