apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}-active
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
    app: {{ .Values.webapp.name }}
    component: web         
spec:
  ports:
  - name: http
    port: {{ .Values.webapp.container.port }}
    targetPort: http