apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.webapp.name }}-web-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
      component: web
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.webapp.name }}-worker-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}-worker
      component: worker
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.webapp.name }}-flower-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.webapp.name }}-flower
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}-flower
      component: flower
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s