apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapp.name }}-active
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
spec:
  ports:
  - name: http
    port: {{ .Values.webapp.container.port }}
    targetPort: {{ .Values.webapp.container.port }}
  - name: metrics
    port: 9090
    targetPort: 8000