apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.webapp.name }}-preview
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
      - {{ .Values.webapp.name }}-preview.k8s.ucar.edu
      secretName: ncote-celery-demo-preview-tls
  rules:
  - host: {{ .Values.webapp.name }}-preview.k8s.ucar.edu  # ncote-celery-demo-preview.k8s.ucar.edu
    http:
      paths:
      - path: {{ .Values.webapp.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-preview
            port:
              number: {{ .Values.webapp.container.port }}
      - path: /flower
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webapp.name }}-flower
            port:
              number: 5555