apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  strategy:
    blueGreen:
      activeService: {{ .Values.webapp.name }}-active
      previewService: {{ .Values.webapp.name }}-preview
      autoPromotionEnabled: false  # Manual promotion for testing
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates: []
        args: []
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      volumes:
        - name: {{ .Values.webapp.volume1.name }}
          nfs:
            server: {{ .Values.webapp.volume1.server }}
            path: {{ .Values.webapp.volume1.path }}
            readOnly: {{ .Values.webapp.volume1.readOnly }}
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: {{ .Values.webapp.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        volumeMounts:
        - mountPath: /glade/campaign
          name: {{ .Values.webapp.volume1.name }}
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"