apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}-worker
    group: {{ .Values.webapp.group }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}-worker
    spec:
      volumes:
        - name: {{ .Values.webapp.volume1.name }}
          nfs:
            server: {{ .Values.webapp.volume1.server }}
            path: {{ .Values.webapp.volume1.path }}
            readOnly: {{ .Values.webapp.volume1.readOnly }}
      containers:
      - name: {{ .Values.webapp.name }}-worker
        image: {{ .Values.webapp.container.image }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 10Gi
        volumeMounts:
        - mountPath: /glade/campaign
          name: {{ .Values.webapp.volume1.name }}
        imagePullPolicy: {{ .Values.webapp.container.imagePullPolicy }}
        args:
            - worker
    