name: Data Flask CICD Pipeline

on: 
  push:
    paths:
      - flask-code/**

jobs:
  docker-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H')" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Provide the current directory as build context 
          context: .
          # Specify where the Dockerfile is located in relation to the repo base path
          file: Dockerfile
          # Enable the push to docker hub
          push: true
          # Provide the tags to apply to the image, this example uses the latest image tag 
          tags: |
            ncote/data-flask:${{ steps.date.outputs.date }}
      - name: Update Helm values.yaml
        run: |
          sed -i "/data-flask/ c\    image: ncote/data-flask:'${{ steps.date.outputs.date }}'" helm-chart/values.yaml
      - name: Update Helm Chart.yaml
        run: |
          sed -i '/appVersion:/ c\appVersion: ${{ steps.date.outputs.date }}' /helm-chart/Chart.yaml
