name: Data Flask CICD Pipeline

on: 
  push:
    paths:
      - flask-code/**
    branches:
      - main

jobs:
  podman-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Install Podman
        run: |
<<<<<<< HEAD
          sudo apt-get remove -y golang-github-containers-image \
          && sudo mkdir -p /etc/apt/keyrings \
          && curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/Release.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null \
          && echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
            https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null \
          && sudo apt-get update -y \
          && sudo apt-get install -y podman skopeo
      - name: Build Podman image
        run: |
          podman build -t ncote/data-flask:${{ steps.date.outputs.date }} .
      - name: Push Podman image to Docker hub
        run: |
          podman push ncote/data-flask:${{ steps.date.outputs.date }}
=======
          apt-get -y install podman
      - name: Build and push Podman image
        uses: docker/build-push-action@v4
        with:
          # Provide the current directory as build context 
          context: .
          # Specify where the Dockerfile is located in relation to the repo base path
          file: Dockerfile
          # Enable the push to docker hub
          push: true
          # Provide the tags to apply to the image, this example uses the latest image tag 
          tags: |
            ncote/data-flask:${{ steps.date.outputs.date }}
>>>>>>> ca2ae1e (Install podman)
      - name: Update Helm values.yaml
        run: |
          sed -i "/data-flask/ c\    image: hub.k8s.ucar.edu/docker/ncote/data-flask:${{ steps.date.outputs.date }}" Charts/helm-chart/values.yaml
      - name: Update Helm Chart.yaml
        run: |
          sed -i "/appVersion:/ c\appVersion: ${{ steps.date.outputs.date }}" Charts/helm-chart/Chart.yaml
      - name: Run python script to update version by 1
        run: python scripts/update_ver.py
      - name: Push changes to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -a -m "Update Helm chart via GH Actions"
          git push
      - name: create pull request
        run: gh pr create -B main -H dev --title 'Merge dev into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
