name: Data Flask CICD Pipeline

on: 
  workflow_dispatch:
  push:
    paths:
      - flask-code/**
    branches:
      - main

jobs:
  podman-build-push:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Build Podman image
        run: |
          podman build -t hub.k8s.ucar.edu/ncote/data-flask:${{ steps.date.outputs.date }} .
      # Login to Harbor with a robot account for the ncote project in Harbor
      - name: Login to Harbor
        run: podman login hub.k8s.ucar.edu -u robot-ncote+dataflask -p ${{ secrets.HARBOR_ROBOT_PW  }}
      - name: Push Podman image to Docker hub
        run: podman push hub.k8s.ucar.edu/ncote/data-flask:${{ steps.date.outputs.date }}
      - name: Update Helm values.yaml
        run: |
          sed -i "/data-flask/ c\    image: hub.k8s.ucar.edu/ncote/data-flask:${{ steps.date.outputs.date }}" Charts/helm-chart/values.yaml
      - name: Update Helm Chart.yaml
        run: |
          sed -i "/appVersion:/ c\appVersion: ${{ steps.date.outputs.date }}" Charts/helm-chart/Chart.yaml
      - name: Run python script to update version by 1
        run: python scripts/update_ver.py
      - name: Push changes to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -a -m "Update Helm chart via GH Actions"
          git push
      - name: create pull request
        run: gh pr create -B main -H dev --title 'Merge dev into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
