name: Django CICD Pipeline

on: 
  push:
    paths:
      - wagtail/**
    branches:
      - dev
permissions:
  contents: read

jobs:
  container-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v3
        with:
          ref: dev
      # Step 2 is to login to docker hub so the image can be pushed
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        # GitHub secrets are used to provide login information to docker hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      # Build and push the image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          # Provide the current directory as build context 
          context: wagtail/cirrus_demo/.
          # Specify where the Dockerfile is located in relation to the repo base path
          file: Dockerfile
          # Enable the push to docker hub
          push: true
          # Provide the tags to apply to the image, this example uses the latest image tag 
          tags: ncote/django-dev:${{ steps.date.outputs.date }}
      
