name: Data Flask DEV CICD Pipeline

on: 
  push:
    branches:
      - dev

env:
  GITHUB_BRANCH: ${{ github.ref_name }}

jobs:
  podman-build-push:
    runs-on: ubuntu-latest
    outputs:
      tagdate: ${{ steps.date.ouputs.date }}
    steps:
      # Get the date to apply to image tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
  show_output:
    runs-on: ubuntu-latest
    needs: podman-build-push
    steps:
      - name: output
        run: echo ${{ needs.podman-build-push.outputs.tagdate }}