name: Data Flask DEV CICD Pipeline

on: 
  push:
    branches:
      - dev

env:
  GITHUB_BRANCH: ${{ github.ref_name }}

jobs:
  podman-build-push:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tagdate.outputs.date }}
    steps:
      # Get the date to apply to image tag
      - name: Get current date
        id: tagdate
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Login to Harbor
        run: docker login hub.k8s.ucar.edu -u robot-ncote+dataflask -p ${{ secrets.HARBOR_ROBOT_PW  }}
  show_output:
    runs-on: ubuntu-latest
    needs: podman-build-push
    steps:
      - env:
          OUTPUT1: ${{ needs.podman-build-push.outputs.output1 }}
        run: echo $OUTPUT1