name: Data Flask DEV CICD Pipeline

on: 
  workflow_dispatch:
  push:
    paths:
      - flask-code/**
    branches:
      - dev
permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_BRANCH: ${{ github.ref_name }}

jobs:
  podman-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: registry login
        uses: docker/login-action@v3
        with:
          registry: hub.k8s.ucar.edu/ncote
          username: robot&ncote+dataflask
          password: ${{ secrets.HARBOR_ROBOT_PW  }}
      - name: Build Podman image
        run: |
          docker buildx build -t hub.k8s.ucar.edu/ncote/data-flask:${{ steps.date.outputs.date }} .
      - name: Push Podman image to Docker hub
        run: docker push hub.k8s.ucar.edu/ncote/data-flask:${{ steps.date.outputs.date }}
      - name: Update Helm values.yaml
        run: |
          sed -i "/data-flask/ c\    image: hub.k8s.ucar.edu/ncote/data-flask-${{ env.GITHUB_BRANCH }}:${{ steps.date.outputs.date }}" Charts/test-helm-chart/values.yaml
      - name: Update Helm Chart.yaml
        run: |
          sed -i "/appVersion:/ c\appVersion: ${{ steps.date.outputs.date }}" Charts/test-helm-chart/Chart.yaml
      - name: Run python script to update version by 1
        run: python scripts/update_test_ver.py
      - name: Push changes to GitHub
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git commit -a -m "Update Helm chart via GH Actions"
          git push

